language: python

python:

  -'3.4'

install:
  - pip install r requirements.txt
script:
  # - python test_user.py
  - python test_question.py
  # - python -m pytest --cov-report term-missing --cov=app
after_sucess:
  - "coveralls"
cache: pip